

-- ------------------------------------------------------------------------------
-- This is auto-generated SQL script.
-- ------------------------------------------------------------------------------
-- This DDL was generated by 'Devart SSDLToMySql.tt' template.
-- SQL is generated on: 06/17/2014 19:09:12
-- Generated from EDMX file: F:\Users\Nick\Documents\TBD2\Shuppet\Shuppet\ShuppetServiceLibrary\ShuppetModel.edmx
-- ------------------------------------------------------------------------------
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;


-- ------------------------------------------------------------------------------
-- Creating all tables
-- ------------------------------------------------------------------------------

-- Table `User`
CREATE TABLE `User`  ( 
    `Id` int NOT NULL AUTO_INCREMENT UNIQUE,
    `username` longtext NOT NULL,
    `password` longtext NOT NULL,
    `cashAmount` double NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE = INNODB;

-- Table `Order`
CREATE TABLE `Order`  ( 
    `Id` int NOT NULL AUTO_INCREMENT UNIQUE,
    `orderDate` datetime NOT NULL,
    `Product_Id` int NOT NULL,
    `User_Id` int NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE = INNODB;

-- Table `Product`
CREATE TABLE `Product`  ( 
    `Id` int NOT NULL AUTO_INCREMENT UNIQUE,
    `name` longtext NOT NULL,
    `price` double NOT NULL,
    `amount` int NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE = INNODB;

-- ------------------------------------------------------------------------------
-- Creating all foreign keys
-- ------------------------------------------------------------------------------

ALTER TABLE `Order`
ADD CONSTRAINT `FK_ProductOrder` FOREIGN KEY (`Product_Id`)
    REFERENCES `Product` (`Id`)
    ON UPDATE NO ACTION;

ALTER TABLE `Order`
ADD CONSTRAINT `FK_UserOrder` FOREIGN KEY (`User_Id`)
    REFERENCES `User` (`Id`)
    ON UPDATE NO ACTION;

/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;
